org.gradle.jvmargs=-Xlog:gc*:file=/home/runner/work/Telltale/Telltale/gradle_gc.log -Xmx5g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8  -XX:MaxMetaspaceSize=1g
kotlin.daemon.jvmargs=-Xlog:gc*:file=/home/runner/work/Telltale/Telltale/kotlin_gc.log -Dfile.encoding=UTF-8  -XX:SoftRefLRUPolicyMSPerMB=1 -XX:ReservedCodeCacheSize=320m -XX:+HeapDumpOnOutOfMemoryError -Xmx4g -Xms4g

android.useAndroidX=true
org.gradle.cache=true
ksp.useKSP2=false
